remote_theme: nathanclevenger/landing

icon: ðŸš€
name: Test.Page.as
description: Get your idea launched in seconds with simplest and most easy-to-use landing page template you've ever worked with.
color: indigo
